version: "3.3"
services:
  dsl_exporter:
    build: ./
    restart: always
    ports:
      - "9091:8000"
  weather_exporter:
    build:
      context: ./
      dockerfile: weather.Dockerfile
    restart: always
    ports:
      - "9093:8000"
    environment:
      - PIRATE_WEATHER_API_KEY
      - LAT_LONG
  speedtest_exporter:
    image: "ghcr.io/danopstech/speedtest_exporter:latest"
    restart: always
    ports:
      - "9092:9090"
  prometheus:
    image: "prom/prometheus:v2.26.0"
    restart: always
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./data/prometheus
        target: /prometheus
  grafana:
    image: "grafana/grafana:7.5.4"
    restart: always
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=ae3e-plotly-panel
    volumes:
      - type: bind
        source: ./data/grafana
        target: /var/lib/grafana
      - type: bind
        source: ./config/grafana/provisioning
        target: /etc/grafana/provisioning/
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
