{
 "title": "DSL",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAN Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(connection_state{connection_state=\"Connected\"}*1) + scalar(connection_state{connection_state=\"Offline\"}*2) + scalar(connection_state{connection_state=\"Down\"}*3)"
    }
   ]
  },
  {
   "title": "DSL Line Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "link1_uptime", "legendFormat": "Link 1" },
    { "expr": "link2_uptime", "legendFormat": "Link 2" }
   ]
  },
  {
   "title": "SN Margin (dB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sn_margin_db", "legendFormat": "{{link}}: {{direction}}" }
   ]
  },
  {
   "title": "HEC Error Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hec_error_count", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  {
   "title": "Super Frame Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "superframe_error_count", "legendFormat": "{{link}} : {{direction}}" }
   ]
  },
  {
   "title": "Outdoor Temp (℉)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "outdoor_temperature_f" }
   ]
  },
  {
   "title": "Cloud Coverage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "outdoor_cloud_cover_pct" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    { "expr": "outdoor_wind_speed_mph", "legendFormat": "Speed" },
    { "expr": "outdoor_wind_gust_mph", "legendFormat": "Gusts" }
   ]
  }
 ]
}