global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'dsl'
    scrape_interval: 1s
    scrape_timeout:  1s
    static_configs:
      - targets: ['dsl_exporter:8000']
  - job_name: 'speedtest'
    scrape_interval: 30m
    scrape_timeout: 40s
    static_configs:
      - targets: [ 'speedtest_exporter:9090' ]
  - job_name: 'weather'
    scrape_interval: 10m
    scrape_timeout:  10s
    static_configs:
      - targets: ['weather_exporter:8000']